// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SJewls.Infrastructure.Data;

#nullable disable

namespace SJewls.Infrastructure.Migrations
{
    [DbContext(typeof(SJewlsDbContext))]
    [Migration("20261008121410_AddJewelleryPlanCategories")]
    partial class AddJewelleryPlanCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SJewls.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituDraw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChituPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DrawDate")
                        .HasColumnType("date");

                    b.Property<int>("DrawMonthIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecordedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WinningSlotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChituPlanId");

                    b.HasIndex("RecordedByStaffId");

                    b.HasIndex("WinningSlotId");

                    b.ToTable("ChituDraws");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituInstalment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("ChituSlotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("MonthIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChituSlotId", "MonthIndex")
                        .IsUnique();

                    b.ToTable("ChituInstalments");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChituBenefitValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DueDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyInstalmentAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSlotCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("ChituPlans");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChituPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosureRemarks")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReservedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ChituPlanId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("ChituSlots");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ClosureRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ApprovedRefundAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CancellationFeeCharged")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionRemarks")
                        .HasColumnType("text");

                    b.Property<Guid>("JewelleryEnrolmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByStaffId");

                    b.HasIndex("JewelleryEnrolmentId");

                    b.ToTable("ClosureRequests");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosureReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeactivatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeactivationReason")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MergedIntoCustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrimaryBranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeactivatedByStaffId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Nic")
                        .IsUnique()
                        .HasFilter("\"Nic\" IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.HasIndex("PrimaryBranchId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ExtensionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionRemarks")
                        .HasColumnType("text");

                    b.Property<Guid>("JewelleryEnrolmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestedExtensionMonths")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByStaffId");

                    b.HasIndex("JewelleryEnrolmentId");

                    b.ToTable("ExtensionRequests");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.GoldRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Karat")
                        .HasColumnType("integer");

                    b.Property<decimal>("RatePerGram")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("RecordedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RecordedByStaffId");

                    b.ToTable("GoldRates");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AppliedRatePerGram")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrencyAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("GoldGrams")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("JewelleryEnrolmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Karat")
                        .HasColumnType("integer");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JewelleryEnrolmentId");

                    b.HasIndex("PaymentId");

                    b.ToTable("JewelleryContributions");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryEnrolment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JewelleryPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectedDurationMonths")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TargetEndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TargetProductWeightGrams")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalContributedCurrency")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalSavedGrams")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalTargetCurrency")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JewelleryPlanId");

                    b.ToTable("JewelleryEnrolments");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int[]>("AllowedDurationsMonths")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<int>("CancellationFeeType")
                        .HasColumnType("integer");

                    b.Property<decimal>("CancellationFeeValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Karat")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TargetMakingCharges")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TargetProductGoldWeightGrams")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TargetVat")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalTargetAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JewelleryPlans");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryPlanCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("JewelleryCategories");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ResendCooldownUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactValue", "Purpose", "IsConsumed");

                    b.ToTable("OtpChallenges");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<int>("Module")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RecordedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdempotencyKey");

                    b.HasIndex("ProviderReference");

                    b.HasIndex("RecordedByStaffId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.PaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("AllocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentAllocations");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.PaymentQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AppliedRatePerGram")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrencyAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GoldGrams")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Karat")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PaymentQuotes");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.PhysicalClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HandedOverByStaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Module")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HandedOverByStaffId");

                    b.ToTable("PhysicalClaims");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("NetRefundAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByStaffId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.RegistrationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RegistrationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationToken")
                        .IsUnique();

                    b.ToTable("RegistrationSessions");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeactivatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeactivationReason")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.StaffBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("StaffId", "BranchId")
                        .IsUnique();

                    b.ToTable("StaffBranches");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.StaffRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("StaffId", "RoleId")
                        .IsUnique();

                    b.ToTable("StaffRoles");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.WinnerBenefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChituBenefitValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("ChituDrawId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChituSlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimRemarks")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HandedOverByStaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChituDrawId")
                        .IsUnique();

                    b.HasIndex("ChituSlotId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("HandedOverByStaffId");

                    b.ToTable("WinnerBenefits");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituDraw", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.ChituPlan", "ChituPlan")
                        .WithMany("Draws")
                        .HasForeignKey("ChituPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Staff", "RecordedByStaff")
                        .WithMany()
                        .HasForeignKey("RecordedByStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.ChituSlot", "WinningSlot")
                        .WithMany()
                        .HasForeignKey("WinningSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChituPlan");

                    b.Navigation("RecordedByStaff");

                    b.Navigation("WinningSlot");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituInstalment", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.ChituSlot", "ChituSlot")
                        .WithMany("Instalments")
                        .HasForeignKey("ChituSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChituSlot");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituPlan", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Branch", "Branch")
                        .WithMany("ChituPlans")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituSlot", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.ChituPlan", "ChituPlan")
                        .WithMany("Slots")
                        .HasForeignKey("ChituPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Customer", "Customer")
                        .WithMany("ChituSlots")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChituPlan");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ClosureRequest", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Staff", "DecidedByStaff")
                        .WithMany()
                        .HasForeignKey("DecidedByStaffId");

                    b.HasOne("SJewls.Domain.Entities.JewelleryEnrolment", "JewelleryEnrolment")
                        .WithMany("ClosureRequests")
                        .HasForeignKey("JewelleryEnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedByStaff");

                    b.Navigation("JewelleryEnrolment");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Customer", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Staff", "DeactivatedByStaff")
                        .WithMany()
                        .HasForeignKey("DeactivatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SJewls.Domain.Entities.Branch", "PrimaryBranch")
                        .WithMany("Customers")
                        .HasForeignKey("PrimaryBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeactivatedByStaff");

                    b.Navigation("PrimaryBranch");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ExtensionRequest", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Staff", "DecidedByStaff")
                        .WithMany()
                        .HasForeignKey("DecidedByStaffId");

                    b.HasOne("SJewls.Domain.Entities.JewelleryEnrolment", "JewelleryEnrolment")
                        .WithMany("ExtensionRequests")
                        .HasForeignKey("JewelleryEnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedByStaff");

                    b.Navigation("JewelleryEnrolment");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.GoldRate", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Branch", "Branch")
                        .WithMany("GoldRates")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Staff", "RecordedByStaff")
                        .WithMany()
                        .HasForeignKey("RecordedByStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("RecordedByStaff");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryContribution", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.JewelleryEnrolment", "JewelleryEnrolment")
                        .WithMany("Contributions")
                        .HasForeignKey("JewelleryEnrolmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JewelleryEnrolment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryEnrolment", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Customer", "Customer")
                        .WithMany("JewelleryEnrolments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.JewelleryPlan", "JewelleryPlan")
                        .WithMany("Enrolments")
                        .HasForeignKey("JewelleryPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("JewelleryPlan");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryPlan", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Branch", "Branch")
                        .WithMany("JewelleryPlans")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.JewelleryPlanCategory", "Category")
                        .WithMany("JewelleryPlans")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryPlanCategory", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Branch", "Branch")
                        .WithMany("JewelleryCategories")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Staff", "RecordedByStaff")
                        .WithMany()
                        .HasForeignKey("RecordedByStaffId");

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("RecordedByStaff");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Payment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.PhysicalClaim", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Staff", "HandedOverByStaff")
                        .WithMany()
                        .HasForeignKey("HandedOverByStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("HandedOverByStaff");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Customer", "Customer")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Refund", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Staff", "ApprovedByStaff")
                        .WithMany()
                        .HasForeignKey("ApprovedByStaffId");

                    b.HasOne("SJewls.Domain.Entities.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByStaff");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.StaffBranch", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Branch", "Branch")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Staff", "Staff")
                        .WithMany("AssignedBranches")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.StaffRole", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.Role", "Role")
                        .WithMany("StaffMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Staff", "Staff")
                        .WithMany("Roles")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.WinnerBenefit", b =>
                {
                    b.HasOne("SJewls.Domain.Entities.ChituDraw", "ChituDraw")
                        .WithOne("Benefit")
                        .HasForeignKey("SJewls.Domain.Entities.WinnerBenefit", "ChituDrawId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.ChituSlot", "ChituSlot")
                        .WithOne("WinnerBenefit")
                        .HasForeignKey("SJewls.Domain.Entities.WinnerBenefit", "ChituSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SJewls.Domain.Entities.Staff", "HandedOverByStaff")
                        .WithMany()
                        .HasForeignKey("HandedOverByStaffId");

                    b.Navigation("ChituDraw");

                    b.Navigation("ChituSlot");

                    b.Navigation("Customer");

                    b.Navigation("HandedOverByStaff");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Branch", b =>
                {
                    b.Navigation("ChituPlans");

                    b.Navigation("Customers");

                    b.Navigation("GoldRates");

                    b.Navigation("JewelleryCategories");

                    b.Navigation("JewelleryPlans");

                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituDraw", b =>
                {
                    b.Navigation("Benefit");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituPlan", b =>
                {
                    b.Navigation("Draws");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.ChituSlot", b =>
                {
                    b.Navigation("Instalments");

                    b.Navigation("WinnerBenefit");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Customer", b =>
                {
                    b.Navigation("ChituSlots");

                    b.Navigation("JewelleryEnrolments");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryEnrolment", b =>
                {
                    b.Navigation("ClosureRequests");

                    b.Navigation("Contributions");

                    b.Navigation("ExtensionRequests");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryPlan", b =>
                {
                    b.Navigation("Enrolments");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.JewelleryPlanCategory", b =>
                {
                    b.Navigation("JewelleryPlans");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Role", b =>
                {
                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("SJewls.Domain.Entities.Staff", b =>
                {
                    b.Navigation("AssignedBranches");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
